# Use lots of codegen units in dev so crates build in parallel
[profile.dev]
opt-level = 1
debug = 1
codegen-units = 256
incremental = true

# For release builds (tauri build), keep thin LTO (fast) and fewer codegen units
[profile.release]
lto = "thin"
codegen-units = 16
incremental = false

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=mold"]

[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"