name: CI (Linux build)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-linux:
    runs-on: ubuntu-24.04

    permissions:
      contents: read

    env:
      # make Vite builds deterministic in CI
      NODE_ENV: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # System deps required by Tauri v2 on Linux
      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.1-dev \
            build-essential \
            curl \
            wget \
            libgtk-3-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev

      # Rust toolchain
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      # Node + pnpm (with cache of the pnpm store)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: |
            pnpm-lock.yaml
            **/pnpm-lock.yaml

      - name: Enable corepack (for pnpm)
        run: corepack enable

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Install JS deps
        run: pnpm install --frozen-lockfile

      # Optional: verify Rust deps resolve (helps fail-fast on lock issues)
      - name: Cargo fetch
        working-directory: src-tauri
        run: cargo fetch

      # Build (your tauri.conf.json already defines beforeBuildCommand)
      - name: Build Tauri (Linux)
        run: pnpm tauri build

      - name: Upload Linux bundles
        uses: actions/upload-artifact@v4
        with:
          name: linux-bundles
          path: |
            src-tauri/target/release/bundle/**/*.AppImage
            src-tauri/target/release/bundle/deb/**/*.deb
            src-tauri/target/release/bundle/**/latest.json
          if-no-files-found: warn